name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: 'write'
  attestations: 'write'
  contents: 'write'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f
      with:
        version: 0.14.1
    - name: "Build"
      run: |
        mkdir dist
        # zig build -Doptimize=ReleaseSmall -Dtarget=x86-linux-gnu
        # mv zig-out/lib/*.so dist/c-wspp-linux-x86.so
        zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-linux-gnu
        mv zig-out/lib/*.so dist/c-wspp-linux-amd64.so
        zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-macos
        mv zig-out/lib/*.dylib dist/c-wspp-macos-amd64.dylib
        zig build -Doptimize=ReleaseSmall -Dtarget=x86-windows
        mv zig-out/bin/*.dll dist/c-wspp-win32.dll
        zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-windows
        mv zig-out/bin/*.dll dist/c-wspp-win64.dll
    - name: Install release dependencies
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install 7zip
    - name: Set env
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    - name: Bundle release zip
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        RELEASE_NAME=c-wszig-bin-all_`echo ${{ env.RELEASE_VERSION }} | tr '.' '-'`
        cp -r -- dist "$RELEASE_NAME"
        cp -- LICENSE "$RELEASE_NAME/c-wspp-license.txt"
        7zz -mx=9 a -- "dist/$RELEASE_NAME.zip" "$RELEASE_NAME"  # change 7zz to 7z for ubuntu-24.04
        rm -r -- "$RELEASE_NAME"
    - name: Attest builds
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: |
          dist/*
    - name: Store dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          dist
          !dist/*.zip
        compression-level: 9
        if-no-files-found: error
    - name: Create Release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: softprops/action-gh-release@975c1b265e11dd76618af1c374e7981f9a6ff44a
      with:
        draft: true
        name: c-wszig v${{ env.RELEASE_VERSION }}
        files: 'dist/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
