name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**.zig'
      - '**.zig.zon'
      - '.github/workflows/test.yaml'
  pull_request:
    paths:
      - '**.zig'
      - '**.zig.zon'
      - '.github/workflows/test.yaml'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f
        with:
          version: 0.14.1
      - name: Run Tests
        timeout-minutes: 10  # this step may compile a lot
        run: |
          zig build test
      - name: Run sample (Debug)
        timeout-minutes: 2
        run: |
          zig build run
      - name: Run sample (Release)
        timeout-minutes: 10  # this step may compile a lot
        run: |
          zig build run -Doptimize=ReleaseSmall
