name: Test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f
        with:
          version: 0.14.1
      - name: Run Tests
        run: |
          zig build test
      - name: Run sample
        run: |
          zig build run
